name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          python -m venv ./venv
          source venv/bin/activate

      - run: |
          pip install pytest pytest-cov

      - run: make test
